apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcolor
spec:
  selector:
    matchLabels:
      app: webcolor
  template:
    metadata:
      labels:
        app: webcolor
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '80'
    spec:
      containers:
      - name: webcolor
        image: fabricioveronez/web-color:blue
        ports:
        - containerPort: 80
