apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: poc-python
  namespace: argocd
spec:
  project: poc-python
  source:
    repoURL: https://github.com/Alves0611/health-api
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
