apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alves0611/health-api
    targetRevision: HEAD
    path: argocd/install
  revisionHistoryLimit: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
