apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Alves0611/health-api
    targetRevision: HEAD
    path: k8s
  revisionHistoryLimit: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: webcolor
      namespace: default
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      name: webcolor
      namespace: default
      jsonPointers:
        - /status/currentReplicas
        - /status/desiredReplicas

